services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        
    Kematjaya\ChartBundle\Builder\ChartBuilderInterface:
        class: Kematjaya\ChartBundle\Builder\ChartBuilder
        
    Kematjaya\ChartBundle\Builder\ChartRendererBuilderInterface:
        class: Kematjaya\ChartBundle\Builder\ChartRendererBuilder
        
    Kematjaya\ChartBundle\Renderer\PieChartRenderer: ~
    Kematjaya\ChartBundle\Renderer\LineChartRenderer: ~
    Kematjaya\ChartBundle\Renderer\ColumnChartRenderer: ~
        
    Kematjaya\ChartBundle\Twig\ChartExtension:
        tags: ['twig.extension']